rootProject.name = "orm-workshop"
include("exercise1")
include("solution1-via-entity-manager")
include("solution1-via-repository")
include("exercise2")
include("exercise2-simplified")
include("solution2")
include("solution3")
include("exercise3")
include("exercise4")
include("solution4")
include("table-per-class-solution")
include("single-table-solution")
