version: '3.7'
services:
  postgres:
    image: postgres
    restart: always
    container_name: orm-workshop-postgresql
    ports:
      - "5432:5432"
    volumes:
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    environment:
      POSTGRES_PASSWORD: root_pw
